define([], function() {
  return {
    "PropertyPaneDescription": "Description",
    "BasicGroupName": "Group Name",
    "DescriptionFieldLabel": "Description Field",
    "WebPartTitle":"Welcome to use SharePoint Online Quick Assist!",
    "SearchIssue":"Search Issues",
    "SpecifiedDocument":"Specified Document",
    "SpecifiedSite":"Specified Site",
    "UserProfileIssues":"UserProfile Issues",
    "Photosync":"Photo sync",
    "JobTitlesync":"Job Title sync",
    "Userinformationsync":"User information sync",
    "OneDriveIssues":"OneDrive Issues",
    "OneDrivelockicon":"OneDrive lock icon",
    "ListLibraryIssues":"List/Library Issues",
    "MissingForms":"Missing New/Disp/Edit Forms",
    "Uneditablewikipage":"Uneditable wiki page",
    "Site":"Site",
    "RestoreItems":"Restore Items",
    "GetFileChanges":"Get File Changes (New/Update)",
    "Permissionissue":"Permission issue",
    "SelectIssueTip":"Please select issue which you want to check",
    "AffectedUser":"Affected User:",
    "AffectedSiteLoadList":"Affected Site(press enter for loading libraries/lists):",
    "AffectedSite":"Affected Site:",
    "SelectList":"Please select the affected library/list:",
    "AffectedDocument":"Affected document full URL:",
    "CheckIssues":"Check Issues",
    "ShowRemedySteps":"Show Remedy Steps",
    "FailedLoadSiteList":"Failed to load lists from the site, please make sure the site URL is correct and you have the permssion, detail error is",
    "PleaseSelectList":"Please select the library!",
    "Checking":"Checking",
    "DiagnoseResult":"Diagnose Result:",    
    "PC_DocumentsWithoutCheckin":"There are documents without check-in version in the library.",
    "PC_NoDocumentsWithoutCheckin":"There isn't any documents without check-in version in the library.",
    "PC_ApproveStatusIs":"'s approve status is",
    "PC_FileExistingMsg":"The file can be found.",
    "PC_FileNotExistingMsg":"The file can't be found.",
     "PC_PageCustomized":"This page contains customzations",
     "PC_UserHasPermssionOnDocument":"The user has enough permission to read the document",
     "PC_UserHasNoPermssionOnDocument":"The user lacks enough permission to read the document",
     "PC_DocumentIsInDraft":"The document is in draft version",
     "PC_DocumentIsNotInDraft":"The document isn't in draft version",
     "PC_ListSecurityLevelHasIssue":"The library has been set to only the author can read/write the item",
     "PC_ListSecurityLevelHasNoIssue":"The library hasn't been set to only the author can read/write the item",
     "PC_LockDownEnabled":"Limited-access user permission lockdown mode of the site collection has been enabled",
     "PC_LockDownNotEnabled":"Limited-access user permission lockdown mode of the site collection hasn't been enabled",
     "PC_HasViewPermissionOnList":"The affected user has enough permission to view the library.",
     "PC_HasNoViewPermissionOnList":"The affected user hasn't enough permission to view the library.",
     "PC_TryDisable3PCode":"Try to disable 3rd party code by appending ?disable3PCode to page URL and open it in a new tab",
     "PC_LackPermissionOn":"The affected user lacks permission,",
     "PC_CanNotLoad":"can't be loaded!", 
     "RemedySteps":"Remedy Steps:",
     "CanBeFixedIn":"can be fixed in",
     "ThisPage":"this page",   
     "RI_DeletedBy":"Deleted By:",
     "RI_PathFilter":"Path Filter",
     "RI_StartDate":"Start Date",
     "RI_SelectADate":"Select a date...",
     "RI_EndDate":"End Date",
     "RI_QueryItems":"Query Items",
     "RI_Restore":"Restore",
     "RI_Export":"Export",
     "RI_Querying":"Querying",    
     "RI_DeletedDate":"DeletedDate",
     "RI_Path":"Path",
     "RI_DeletedByEmail":"DeletedByEmail",
     "RI_DeletedByName":"DeletedByName",
     "RI_NoData":"No Data",
     "RI_FullDocumentPath":"The document full path",
     "RI_NotMatchListRootFolder":"doesn't match list root folder",
     "RI_FailedToLoadItem":"Failed to load item via {0}",
     "RI_URLInvalid":"is not a valid URL or the item doesn't exist",
     "RI_ItemTypeUnKnow":"ItemType is UnKnown",
     "RI_FailedToGetData":"Failed to get data from request",
     RI_QueryResult:"Queried {0} items, filtered {1} items in {2} in seconds.",
     RI_QueryProgress:"Queried {0} items, filtered {1} items ......",
     RI_RestoreProgress:"Restoring item from {0} to {1}, please wait ......",
     RI_RestoreResult:"Restored {0} items in {1} seconds.",
     RI_RestoreResultWithError:"Restoring item from {0} to {1} with error message:{2}",
     "SD_DocumentPathCanNotBeNull":"Please provide the affected document full URL!",
     "SD_DocumentCanBeSearched":"The document can be searched.",
     "SD_SearchByFullPathException":"Get exception when trying to SearchDocumentByFullPath with error message",
     "SD_IsWebNoCrawlException":"Get exception when trying to check IsWebNoCrawl with error message",
     "SD_DectectedNocrawlList":"Dectected nocrawl for the list.",
     "SD_IsListNoCrawlException":"Get exception when try to check IsListNoCrawl with error message",
     "SD_DectectedDisplayFormIsMissing":"Dectected display form is missing, please use the feature \"Missing New/Disp/Edit Forms\" to fix it",
     "SD_IsListMissDisplayFormException":"Get exception when trying to check IsListMissDisplayForm with error message",
     "SD_TheNocrawlEnabledList":"The nocrawl has been enabled for the list",
     "SD_TheNocrawlNotEnabledList":"The nocrawl hasn't been enabled for the list",
     "SD_TheDisplayFormMissed":"The dispalyForm is missed for the list",
     "SD_TheDisplayFormNotMissed":"The dispalyForm isn't missed for the list",
     "SD_IsDocumentInDraftVersionException":"Get exception when trying to check IsDocumentInDraftVersion with error message",
     "SD_FolderSkipDraftCheck":"is a folder, skip draft version checking",
     "SD_DectectedNocrawlSite":"Dectected nocrawl for the site",
     "SD_NocrawlEnabledSite":"The nocrawl has been enabled for the site",
     "SD_NocrawlNotEnabledSite":"The nocrawl hasn't been enabled for the site",
     "OL_CheckingIssueForLibrary":"Checking issue for library",
     "OL_LockdownEanbled":"Limited-access user permission lockdown mode of the site collection has been enabled",
     "OL_LockdownNotEanbled":"Limited-access user permission lockdown mode of the site collection hasn't been enabled",
     "OL_HasEditPermssionOnLibrary":"The affected user has enough permssion to edit the library",
     "OL_LackEditPermssionOnLibrary":"The affected user lack enough permssion to edit the library",
     "OL_OfflineAvailability":"Offline Client Availability for the library has been set to",
     "OL_RequireCheckOut":"Require Check Out for the library has been set to",
     "OL_DraftItemSecurity":"Draft Item Security of this library has been set to",
     "OL_AnyUserCanRead":"Any user who can read items",
     "OL_EditUserCanRead":"Only users who can edit items",
     "OL_ApproverCanRead":"Only users who can approve items (and the author of the item)",
     "OL_ContentApproval":"Content Approval of this library has been set to",
     "OL_ValidationFormula":"Validation formula/message of this library is",
     "OL_OfflineAvailabilityForWeb":"Offline Client Availability has been set to",
     "OL_SchemaCheckPassed":"Schema check for this library passed.",
     "OL_ColumnHasBeenSetTo":"the column has been set to",
     "OL_Required":"Required",
     "OL_Formula":"ValidationFormula",
     "OL_ValidationMessage":"ValidationMessage",
     SS_DiagnoseResultLabel:"Diagnose result:",
     SS_FoundSite:"Found site with URL {0}",
     SS_SiteNoExist1:"Site with URL {0} doesn't exist",       
     SS_NoCrawlEnabled1:"The nocrawl setting has been enabled for the site {0} or its parent",      
     SS_SiteIndexEnabled1:"Site {0} is enabled for search index",  
     SS_HaveAccess:"You have access to the site",
     SS_NoAccess:"You don't have 'Read' permissions to the site",
     SS_InMembers:"You are in the 'Members' group of the site",
     SS_NotInMembers:"You are not in the 'Members' group of the site",
     SS_Label_AffectedSite:"Affected Site:",
     SS_Label_CheckIssues:"Check Issues",
     SS_Label_FixIssues:"Fix Issues",
     SS_Message_Checking:"Checking ......",
     SS_Message_NoSearchResult:"No Search Result for the site.",
     SS_Ex_GetWebError:"Get exception when try to get web with error message",
     SS_Ex_IsWebNoCrawlError:"Get exception when try to check IsWebNoCrawl with error message",
     SS_Ex_GetUserInfoError:"Get exception when try to get user info with error message",
     SS_Message_ResultDuplicate:"Search Result in Duplicate for the site.",
     SS_Message_SiteSearchable:"The site is searchable.",
     SS_Message_FixSite:"Fix detected site search issues ......",
     SS_Ex_FixWebNoCrawlError:"Get exception when try to check FixWebNoCrawl with error message",
     SS_Ex_AddUserInMembersError:"Get exception when try to check AddUserinMembers with error message",
     SS_Message_FxiedAll:"Fixed all detected issues please try to reindex the affected site and wait for 20~30 minutes then verify it",
     SS_Message_SearchAndOffline:"Please access 'Search and Offline Availability' and select 'Yes' for 'Indexing Site Content'. ",
     SS_Message_WaitAfterFix:"After fixing all detected issues, please reindex the site and wait for 20~30 minutes then verify it. ",
     SS_Message_CheckPermissions:"Please check your permissions to the site",
     SS_Message_AddInMembers:"This is a group site. Please add yourself as a member of the group. Refer: https://docs.microsoft.com/en-us/sharepoint/troubleshoot/search/search-results-dont-appear-for-group-owners",
     MF_Label_AffectedSite:"Affected Site(press enter for loading libraries/lists):",
     MF_Label_SelectList:"Please select the affected library/list",
     MF_Label_DiagnoseResult:"Diagnose result,",
     MF_Message_DispFormMiss:"The dispForm is missing for",
     MF_Message_DispFormExist:"The dispForm exists",
     MF_Message_NewFormMiss:"The newForm is missing for",
     MF_Message_NewFormExist:"The newForm exists",
     MF_Message_EditFormMiss:"The editForm is missing for",
     MF_Message_EditFormExist:"The editForm exists",
     MF_Ex_LoadListsError:"Failed to load lists from the site, please make sure the site URL is correct and you have the permssion, detail error is",
     MF_Ex_ListNotSelected:"Please select the list/library!",
     MF_Message_CheckingForms:"Checking if the forms exist ......",
     MF_Ex_CheckFormsError:"Get exception when try to check forms with error message",
     MF_Message_FixForms:"Repair missing forms ......",
     MF_Ex_FixDispFormError:"Get exception when try fixing the display form with error message",
     MF_Ex_FixNewFormError:"Get exception when try fixing the new form with error message",
     MF_Ex_FixEditFormError:"Get exception when try fixing the edit form with error message",
     MF_Message_FixedAll:"Fixed all missing forms",
     FC_Label_QuerySite:"Query Site:",
     FC_Lable_ModifedUser:"Modified User:",
     FC_Label_PathFilter:"Path Filter:",
     FC_Label_StartDate:"Start Date:",
     FC_Message_SelectDate:"Select a date...",
     FC_Label_EndDate:"End Date:",
     FC_Label_GetFiles:"Get Files",
     FC_Label_Export:"Export",
     FC_Message_Quering:"Querying ......",
     FC_Ex_GetFilesChangeError:"Get Files Change Exited Unexpectedly",
     FC_Message_QueryDone:"Query Complete. Changes Number:",
     FC_Ex_GetSiteError:"Failed to get the site",
     UI_Label_AffectedSite:"Affected Site",
     UI_Label_Email:"Email of Affected User/Group",
     UI_CheckIssueforUser:"Check Issues",
     UI_FixIssues:"Fix issue",
     UI_Result1:"Display name in AAD is",
     UI_Result2:"display name in user info list is",
     UI_Result3:"Email in AAD is",
     UI_Result4:"email in user info list is",
     UI_Result5:"JobTitle in AAD is",
     UI_Result6:"JobTitle in user info list is",
     UI_Result7:"WorkPhone in AAD is",
     UI_Result8:"WorkPhone in user info list is",
     UI_NonAffectedSite:"Affected site can't be null or invalid!",
     UI_NonAffectedUser:"Affected user can't be null or invalid!",
     UI_FixEmail:"Fixing user info item with eamil",
     UI_NonAADUser:"In the AAD can't find any group or user with the email address",
     UI_NonUserListUser:"In the user info list can't find any user with the UPN",
     UI_OneUserAAD:"Get one user from AAD:",
     UI_OneGroupAAD:"Get one group from AAD",
     UI_NonUserListGroup:"In the user info list can't find any group with group Id", 
     UI_FixSuccess:"Fix in the user info list completed, please recheck for verfiying it.",
     UI_FixFailed:"Fix in the user info list failed.",
     UPD_CheckDepartment:"Check UserProfile Department",
     UPE_CheckEmail:"Check UserProfile Email",
     UPM_CheckManager:"Check UserProfile Manager",
     UPP_PhotoURL:"Picture URL from UAP is",
     UPP_PhotoAAD:"Picture from AAD:",
     UPP_PhotoUserProfile:"Picture from user profile:",
     UPP_PhotoSuccess:"Photos are loaded, but if they are mismatched, please follow this article https://github.com/abrcheng/SharePointOnlineQuickAssist/tree/main/KBs/UAP/SyncPhotoFromADToSPO",
     UPP_PhotoFailed:"Failed to get the user photo from the user profie! Please consider to follow this article https://github.com/abrcheng/SharePointOnlineQuickAssist/tree/main/KBs/UAP/SyncPhotoFromADToSPO",
     UPP_NonAADPhoto:"Failed to get the user photo from the AAD! please consider to set the user photo in AAD https://github.com/abrcheng/SharePointOnlineQuickAssist/tree/main/KBs/UAP/SyncPhotoFromADToSPO",
     UPT_AADTitle:"JobTitle from AAD is",
     UPT_UserProfileTitle:"JobTitle from User Profile is",
     UPT_UserInfoListTitle:"JobTitle from site user info list is",
     UPT_NonAADTitle:"Failed to get the user/job title from AAD!",
     UPT_NonSiteTitle:"Failed to get the user from the site!",
     UPT_FixSiteTitle:"Fixing JobTitle in the site ...",
     UPT_FixUserProfileTitle:"Fixing JobTitle user profile ...",
     UPT_FailedUserProfileTitle :"Fix JobTitle in the user profile failed.",
     UPT_SuccessUserInfoListTitle:"Fix JobTitle in the user info list completed, please recheck for verfiying it.",
     UPT_FailedUserInfoListTitle:"Fix JobTitle in the user info list failed.",
     UW_AffectedWikiPage:"Affected Wiki page:",
     UW_WikiLayout_OneColumn:"One column",
     UW_WikiLayout_OneColumnWithSideBarOrTwoColumn:"One column with sidebar or Two column",
     UW_WikiLayout_TwoColumnWithHeader:"Two column with header",
     UW_WikiLayout_TwoColumnWithHeaderAndFooter:"Two column with header and footer",
     UW_WikiLayout_ThreeColumn:"Three column",
     UW_WikiLayout_ThreeColumnWithHeader:"Three column with header",
     UW_WikiLayout_ThreeColumnWithHeaderAndFooter:"Three column with header and footer",
     UW_WikiLayout_InvalidLayout:"Invalid layout",
     UW_CheckingWikiLayout:"Checking the page layout of {0}......",
     UW_DeclaredLayout:"The page layout has been declared as: {0}",
     UW_DetectedLayout:"The page layout detected from saved HTML elements is: {0}",
     UW_LayoutMatch:"Page layout matches the declaration",
     UW_LayoutNotMatch:"Page layout does not match the declaration",
     UW_IssueDetected:"The page has layout issue which could cause the ribbon menu being grayed-out and the page uneditable. Please check <a href=\"{0}\">this page</a> to fix the issue.",
     UW_NoIssueDetected:"Didn't find any issue.",
     UW_Ex_FailedGetPageInfo:"Failed to get page info, please make sure the page URL is correct and you have the permssion. Detail: {0}"
  }
});