define([], function() {
    return {
      "PropertyPaneDescription": "説明",
      "BasicGroupName": "グループ名 ",
      "DescriptionFieldLabel": "説明フィールド",
      "WebPartTitle":"SharePoint Onlineクイックアシストの使用へようこそ！",
      "SearchIssue":"Search Issues",
      "SpecifiedDocument":"Specified Document",
      "SpecifiedSite":"Specified Site",
      "UserProfileIssues":"UserProfile Issues",
      "Photosync":"Photo sync",
      "JobTitlesync":"Job Title sync",
      "Userinformationsync":"User information sync",
      "OneDriveIssues":"OneDrive Issues",
      "OneDrivelockicon":"OneDrive lock icon",
      "ListLibraryIssues":"List/Library Issues",
      "MissingForms":"Missing New/Disp/Edit Forms",
      "Uneditablewikipage":"Uneditable wiki page",
      "Site":"Site",
      "RestoreItems":"Restore Items",
      "GetFileChanges":"Get File Changes",
      "Permissionissue":"Permission issue",
      "SelectIssueTip":"Please select issue which you want to check",
      "AffectedUser":"Affected User:",
      "AffectedSiteLoadList":"Affected Site(press enter for loading libraries/lists):",
      "AffectedSite":"Affected Site:",
      "SelectList":"Please select the affected library/list:",
      "AffectedDocument":"Affected document full URL:",
      "CheckIssues":"Check Issues",
      "ShowRemedySteps":"Show Remedy Steps",
      "FailedLoadSiteList":"Failed to load lists from the site, please make sure the site URL is correct and you have the permssion, detail error is",
      "PleaseSelectList":"Please select the library!",
      "Checking":"Checking",
      "PC_PermissionUrl":"'s permission issue for URL",
      "PC_DocumentsWithoutCheckin":"There are documents without check-in version in the library.",
      "PC_NoDocumentsWithoutCheckin":"There isn't any documents without check-in version in the library.",
      "PC_ApproveStatusIs":"'s approve status is",
      "PC_FileExistingMsg":"The file can be found.",
      "PC_FileNotExistingMsg":"The file can't be found.",
      "PC_PageCustomized":"This page contains customzations",
      "PC_UserHasPermssionOnDocument":"The user has enough permission to read the document",
      "PC_UserHasNoPermssionOnDocument":"The user lacks enough permission to read the document",
      "PC_DocumentIsInDraft":"The document is in draft version",
      "PC_DocumentIsNotInDraft":"The document isn't in draft version",
      "PC_ListSecurityLevelHasIssue":"The library has been set to only the author can read/write the item",
      "PC_ListSecurityLevelHasNoIssue":"The library hasn't been set to only the author can read/write the item",
      "PC_LockDownEnabled":"Limited-access user permission lockdown mode of the site collection has been enabled",
      "PC_LockDownNotEnabled":"Limited-access user permission lockdown mode of the site collection hasn't been enabled",
      "PC_HasViewPermissionOnList":"The affected user has enough permission to view the library.",
      "PC_HasNoViewPermissionOnList":"The affected user hasn't enough permission to view the library.",
    }
  });