define([], function() {
    return {
      "PropertyPaneDescription": "説明",
      "BasicGroupName": "グループ名",
      "DescriptionFieldLabel": "説明フィールド",
      "WebPartTitle":"SharePoint Online クイックアシストへようこそ！",
      "SearchIssue":"検索に関する不具合",
      "SpecifiedDocument":"特定ドキュメント",
      "SpecifiedSite":"特定サイト",
      "UserProfileIssues":"ユーザープロファイルに関する不具合",
      "Photosync":"画像の同期",
      "JobTitlesync":"役職の同期",
      "Userinformationsync":"ユーザー情報の同期",
      "OneDriveIssues":"OneDrive に関する不具合",
      "OneDrivelockicon":"OneDrive 同期クライアントでロックアイコンが表示されている",
      "ListLibraryIssues":"リスト/ライブラリーに関する不具合",
      "MissingForms":"新規/表示/編集フォームが存在しない",
      "Uneditablewikipage":"Wiki ページが編集できない",
      "Site":"サイト",
      "RestoreItems":"アイテムの復元",
      "GetFileChanges":"ファイルの変更を取得",
      "Permissionissue":"権限に関する不具合",
      "SelectIssueTip":"実施したい診断を指定してください",
      "AffectedUser":"影響を受けているユーザー:",
      "AffectedSiteLoadList":"影響を受けているサイト(Enter キーを押してライブラリーとリストをローディングしてください):",
      "AffectedSite":"影響を受けているサイト:",
      "SelectList":"影響を受けているリスト/ライブラリーを指定してください:",
      "AffectedDocument":"影響を受けているドキュメントの URL:",
      "CheckIssues":"診断",
      "ShowRemedySteps":"対処方法を表示",
      "FailedLoadSiteList":"サイトからリストをロードできませんでした。サイト URL が正しいか、ログインユーザーが必要の権限を持っているかを確認してください。エラー詳細：",
      "PleaseSelectList":"対象ライブラリーを指定してください！",
      "Checking":"診断中",
      "PC_PermissionUrl":"'s permission issue for URL",
      "PC_DocumentsWithoutCheckin":"当該ライブラリー内にチェックインバージョンが存在しないドキュメントがあります。",
      "PC_NoDocumentsWithoutCheckin":"当該ライブラリー内にチェックインバージョンが存在しないドキュメントがありません。",
      "PC_ApproveStatusIs":"の承認状態は",
      "PC_FileExistingMsg":"当該ファイルは存在しています。",
      "PC_FileNotExistingMsg":"当該ファイルを見つかりませんでした。",
      "PC_PageCustomized":"当該ページにカスタマイズ内容が含まれています。",
      "PC_UserHasPermssionOnDocument":"当該ユーザーは当該ドキュメントを閲覧するための権限を持っています。",
      "PC_UserHasNoPermssionOnDocument":"当該ユーザーは当該ドキュメントを閲覧するための権限を持っていません。",
      "PC_DocumentIsInDraft":"当該ドキュメントはドラフト状態になっています。",
      "PC_DocumentIsNotInDraft":"当該ドキュメントはドラフト状態になっていません。",
      "PC_ListSecurityLevelHasIssue":"当該ライブラリーはアイテム作成者しかアイテムを閲覧/編集できないように設定されています。",
      "PC_ListSecurityLevelHasNoIssue":"当該ライブラリーはアイテム作成者しかアイテムを閲覧/編集できないように設定されていません。",
      "PC_LockDownEnabled":"制限付きアクセスのユーザーのアクセス許可ロックダウン モードが有効化されています。",
      "PC_LockDownNotEnabled":"制限付きアクセスのユーザーのアクセス許可ロックダウン モードが有効化されていません。",
      "PC_HasViewPermissionOnList":"当該ユーザーは当該ライブラリーを閲覧するための権限を持っています。",
      "PC_HasNoViewPermissionOnList":"当該ユーザーは当該ライブラリーを閲覧するための権限を持っていません。",
      "PC_TryDisable3PCode":"サードパーティーのコードの影響を除くために、ページ URL の末尾に ?disable3PCode を追加して新しいタブで開いてみてください。",
      "PC_LackPermissionOn":"The affected user lacks permission on",
      "PC_CanNotLoad":"がロードできませんでした！",
      "RemedySteps":"対処方法：",
      "CanBeFixedIn":"こちらで修正できます。",
      "ThisPage":"こちらのページ",   
      "RI_DeletedBy":"削除者:",
      "RI_PathFilter":"パスでフィルダー",
      "RI_StartDate":"開始日時",
      "RI_SelectADate":"日時を指定...",
      "RI_EndDate":"終了日時",
      "RI_QueryItems":"アイテムを復元",
      "RI_Restore":"復元",
      "RI_Export":"エクスポート",
      "RI_Querying":"実行中",
      "RI_Queried":"Queried",
      "RI_Items":"items",
      "RI_Filtered":"filtered",
      "RI_In":"in",
      "RI_RestoreItemFrom":"Restoring item from",
      "RI_Seconds":"seconds",
      "RI_To":"to",
      "RI_PleaseWait":"Please wait",
      "RI_Restored":"Restored",
      "RI_WithErrorMessage":"with error message",
      "RI_DeletedDate":"削除日時",
      "RI_Path":"Path",
      "RI_DeletedByEmail":"削除者のメールアドレス",
      "RI_DeletedByName":"削除者の名前",
      "RI_NoData":"データがありませんでした",
      "RI_FullDocumentPath":"ドキュメントのフルパス",
      "RI_NotMatchListRootFolder":"リストのルートフォルダーに一致しません",
      "RI_FailedToLoadItem":"Failed to load item via",
      "RI_URLInvalid":"は有効な URL ではない、もしくは対象アイテムが存在しません。",
      "RI_ItemTypeUnKnow":"不明なアイテムタイプ",
      "RI_FailedToGetData":"リクエストからデータを取得できませんでした",
      "SD_DocumentPathCanNotBeNull":"影響を受けているドキュメントのフルパスを指定してください！",
      "SD_DocumentCanBeSearched":"当該ドキュメントは検索可能の状態になっています。",
      "SD_SearchByFullPathException":"ドキュメントをフルパスで検索するのを試みる時に例外が発生しました。エラーメッセージ：",
      "SD_IsWebNoCrawlException":"サイトの NoCrwal プロパティを確認する時に例外が発生しました。エラーメッセージ：",
      "SD_DectectedNocrawlList":"当該リストに NoCrawl が有効になっていることを検出しました。",
      "SD_IsListNoCrawlException":"リストの NoCrwal プロパティを確認する時に例外が発生しました。エラーメッセージ：",
      "SD_DectectedDisplayFormIsMissing":"表示フォームが存在しないことを検出しました。\"新規/表示/編集フォームが存在しない\" 診断を実施して修正してください。",
      "SD_IsListMissDisplayFormException":"リストの表示フォームが存在しているかを確認する時に例外が発生しました。エラーメッセージ：",
      "SD_TheNocrawlEnabledList":"当該リストでは NoCrawl が有効になっています。",
      "SD_TheNocrawlNotEnabledList":"当該リストでは NoCrawl が有効になっていません。",
      "SD_TheDisplayFormMissed":"当該リストの表示フォームが存在しません。",
      "SD_TheDisplayFormNotMissed":"当該リストの表示フォームが存在しています。",
      "SD_IsDocumentInDraftVersionException":"当該ドキュメントがドラフト状態になっているかを確認する時に例外が発生しました。エラーメッセージ：",
      "SD_FolderSkipDraftCheck":"はフォルダーであるため、ドラフト状態の確認をスキップします",
      "SD_NocrawlEnabledSite":"当該サイトでは NoCrawl が有効になっています。",
      "SD_NocrawlNotEnabledSite":"当該サイトでは NoCrawl が有効になっていません。",
      "OL_CheckingIssueForLibrary":"ライブラリーを診断中",
      "OL_LockdownEanbled":"当該サイトコレクションでは、制限付きアクセスのユーザーのアクセス許可ロックダウン モードが有効化されています。",
      "OL_LockdownNotEanbled":"当該サイトコレクションでは、制限付きアクセスのユーザーのアクセス許可ロックダウン モードが有効化されていません。",
      "OL_HasEditPermssionOnLibrary":"当該ユーザーは当該ライブラリーを編集するための権限を持っています。",
      "OL_LackEditPermssionOnLibrary":"当該ユーザーは当該ライブラリーを編集するための権限を持っていません。",
      "OL_OfflineAvailability":"当該ライブラリーの「オフライン クライアントの使用制限」設定の値は：",
      "OL_RequireCheckOut":"当該ライブラリーの「チェックアウトを必須にする 」設定の値は：",
      "OL_DraftItemSecurity":"当該ライブラリーの「下書きアイテムのセキュリティ」設定の値は：",
      "OL_AnyUserCanRead":"アイテムを閲覧できるすべてのユーザー",
      "OL_EditUserCanRead":"アイテムを編集できるユーザー",
      "OL_ApproverCanRead":"アイテムの作成者およびアイテムを承認できるユーザー",
      "OL_ContentApproval":"当該ライブラリーの「コンテンツの承認」設定の値は：",
      "OL_ValidationFormula":"当該ライブラリーの検証数式/ユーザー メッセージは：",
      "OL_OfflineAvailabilityForWeb":"当該サイトの「オフライン クライアントの使用制限」設定の値は：",
      "OL_SchemaCheckPassed":"当該ライブラリーはスキーマチェックをパスしました。",
      "OL_ColumnHasBeenSetTo":"the column has been set to",
      "OL_Required":"必須",
      "OL_Formula":"検証数式",
      "OL_ValidationMessage":"検証ユーザー　メッセージ",
      SS_DiagnoseResultLabel:"診断結果：",
      SS_FoundSite:"Found site with URL",
      SS_SiteNoExist1:"Site with URL",
      SS_SiteNoExist2:"doesn't exist",
      SS_NoCrawlEnabled1:"The nocrawl setting has been enabled for the site",
      SS_NoCrawlEnabled2:"or its parent",
      SS_SiteIndexEnabled1:"Site",
      SS_SiteIndexEnabled2:"is enabled for search index",
      SS_HaveAccess:"あなたは当該サイトへのアクセス権限を持っています",
      SS_NoAccess:"あなたは当該サイトの「閲覧」権限を持っていません",
      SS_InMembers:"あなたは当該サイトのメンバーグループに所属しています",
      SS_NotInMembers:"あなたは当該サイトのメンバーグループに所属していません",
      SS_Label_AffectedSite:"影響を受けているサイト：",
      SS_Label_CheckIssues:"診断",
      SS_Label_FixIssues:"修正",
      SS_Message_Checking:"診断中...",
      SS_Message_NoSearchResult:"検索結果がありません。",
      SS_Ex_GetWebError:"当該サイトを取得する時に例外が発生しました。エラーメッセージ：",
      SS_Ex_IsWebNoCrawlError:"サイトの NoCrawl プロパティを確認する時に例外が発生しました。エラーメッセージ：",
      SS_Ex_GetUserInfoError:"ユーザー情報を取得する時に例外が発生しました。エラーメッセージ：",
      SS_Message_ResultDuplicate:"検索結果に重複があります。",
      SS_Message_SiteSearchable:"当該サイトは検索可能になっています。",
      SS_Message_FixSite:"検出しました検索に関する不具合を修正中...",
      SS_Ex_FixWebNoCrawlError:"サイトの NoCrawl 設定を修正する時に例外が発生しました。エラーメッセージ：",
      SS_Ex_AddUserInMembersError:"ユーザーをメンバーグループに追加する時に例外が発生しました。エラーメッセージ：",
      SS_Message_FxiedAll:"検出された不具合を全部修正しました。サイトのインデックスを再構成した上 20 分～ 30 分を待ってから動作を確認してください。",
      SS_Message_SearchAndOffline:"「検索とオフラインでの使用制限」ページにアクセスし、「サイト コンテンツのインデックス処理 」を「はい」に設定してください。",
      SS_Message_WaitAfterFix:"検出された不具合の修正が完了した後には、サイトのインデックスを再構成した上 20 分～ 30 分を待ってから動作を確認してください。",
      SS_Message_CheckPermissions:"サイトへの権限を確認してください。",
      SS_Message_AddInMembers:"当該サイトはグループサイトです。自分をグループメンバーに追加してください。参考資料： https://docs.microsoft.com/en-us/sharepoint/troubleshoot/search/search-results-dont-appear-for-group-owners",
      UI_Label_AffectedSite:"影響を受けているサイト",
      UI_Label_Email:"影響を受けているユーザー/グループのメールアドレス",
      UI_CheckIssueforUser:"診断",
      UI_FixIssues:"修正",
      UI_Result1:"AAD にある表示名は ",
      UI_Result2:"ユーザー情報リストにある表示名は ",
      UI_Result3:"AAD にあるメールアドレスは ",
      UI_Result4:"ユーザー情報リストにあるメールアドレスは ",
      UI_Result5:"AAD にある役職は ",
      UI_Result6:"ユーザー情報リストにある役職は ",
      UI_Result7:"AAD にある勤務先の電話番号は ",
      UI_Result8:"ユーザー情報リストにある勤務先の電話番号は ",
      UI_NonAffectedSite:"影響を受けているサイトの入力が空白または無効です!",
      UI_NonAffectedUser:"影響を受けているユーザーの入力が空白または無効です!",
      UI_FixEmail:"メールアドレスを修正中",
      UI_NonAADUser:"AAD で当該メールアドレスのユーザーまたはグループを見つかりませんでした",
      UI_NonUserListUser:"ユーザー情報リストで当該 UPN のユーザーを見つかりませんでした",
      UI_OneUserAAD:"AAD からユーザーを取得：",
      UI_OneGroupAAD:"AAD からグループを取得：",
      UI_NonUserListGroup:"ユーザー情報リストで当該グループ ID のグループを見つかりませんでした", 
      UI_FixSuccess:"ユーザー情報リストの修正が完了しました。結果を確認してください。",
      UI_FixFailed:"ユーザー情報リストの修正が失敗しました。",
      UPD_CheckDepartment:"ユーザープロファイルでの「部署」を確認",
      UPE_CheckEmail:"ユーザープロファイルでの「メールアドレス」を確認",
      UPM_CheckManager:"ユーザープロファイルでの「上司」を確認",
      UPP_PhotoURL:"UPA からの画像 URL は ",
      UPP_PhotoAAD:"AAD からの画像は ",
      UPP_PhotoUserProfile:"ユーザープロファイルの画像：",
      UPP_PhotoSuccess:"画像をロードできました。もし一致しない場合は、こちらの資料をご参照ください。 https://github.com/abrcheng/SharePointOnlineQuickAssist/tree/main/KBs/UAP/SyncPhotoFromADToSPO",
      UPP_PhotoFailed:"ユーザープロファイルから画像を取得することが失敗しました。こちらの資料をご確認ください。 https://github.com/abrcheng/SharePointOnlineQuickAssist/tree/main/KBs/UAP/SyncPhotoFromADToSPO",
      UPP_NonAADPhoto:"AAD から画像を取得することが失敗しました。AAD で画像を設定してください。 https://github.com/abrcheng/SharePointOnlineQuickAssist/tree/main/KBs/UAP/SyncPhotoFromADToSPO",
      UPT_AADTitle:"AAD からの役職は ",
      UPT_UserProfileTitle:"ユーザープロファイルからの役職は ",
      UPT_UserInfoListTitle:"サイトのユーザー情報リストからの役職は ",
      UPT_NonAADTitle:"AAD から役職を取得することが失敗しました！",
      UPT_NonSiteTitle:"サイトからユーザーを取得することが失敗しました！",
      UPT_FixSiteTitle:"サイトでの役職を修正中...",
      UPT_FixUserProfileTitle:"ユーザープロファイルでの役職を修正中...",
      UPT_FailedUserProfileTitle:"ユーザープロファイルでの役職の修正が失敗しました。",
      UPT_SuccessUserInfoListTitle:"ユーザー情報リストでの役職の修正が完了しました。結果を確認してください。",
      UPT_FailedUserInfoListTitle:"ユーザー情報リストでの役職の修正が失敗しました。"
    }
  });