define([], function() {
    return {
      "PropertyPaneDescription": "説明",
      "BasicGroupName": "グループ名",
      "DescriptionFieldLabel": "説明フィールド",
      "WebPartTitle":"SharePoint Online クイックアシストへようこそ！",
      "SearchIssue":"検索に関する不具合",
      "SpecifiedDocument":"特定ドキュメント",
      "SpecifiedSite":"特定サイト",
      "UserProfileIssues":"ユーザープロファイルに関する不具合",
      "Photosync":"画像の同期",
      "JobTitlesync":"ジョブタイトルの同期",
      "Userinformationsync":"ユーザー情報の同期",
      "OneDriveIssues":"OneDrive に関する不具合",
      "OneDrivelockicon":"OneDrive 同期クライアントでロックアイコンが表示されている",
      "ListLibraryIssues":"リスト/ライブラリーに関する不具合",
      "MissingForms":"新規/表示/編集フォームが存在しない",
      "Uneditablewikipage":"Wiki ページが編集できない",
      "Site":"サイト",
      "RestoreItems":"アイテムの復元",
      "GetFileChanges":"ファイルの変更を取得",
      "Permissionissue":"権限に関する不具合",
      "SelectIssueTip":"実施したい診断を指定してください",
      "AffectedUser":"影響を受けているユーザー:",
      "AffectedSiteLoadList":"影響を受けているサイト(Enter キーを押してライブラリーとリストをローディングしてください):",
      "AffectedSite":"影響を受けているサイト:",
      "SelectList":"影響を受けているリスト/ライブラリーを指定してください:",
      "AffectedDocument":"影響を受けているドキュメントの URL:",
      "CheckIssues":"診断する",
      "ShowRemedySteps":"対処方法を表示",
      "FailedLoadSiteList":"サイトからリストをロードできませんでした。サイト URL が正しいか、ログインユーザーが必要の権限を持っているかを確認してください。エラー詳細：",
      "PleaseSelectList":"対象ライブラリーを指定してください！",
      "Checking":"診断中",
      "PC_PermissionUrl":"'s permission issue for URL",
      "PC_DocumentsWithoutCheckin":"当該ライブラリー内にチェックインバージョンが存在しないドキュメントがあります。",
      "PC_NoDocumentsWithoutCheckin":"当該ライブラリー内にチェックインバージョンが存在しないドキュメントがありません。",
      "PC_ApproveStatusIs":"の承認状態は",
      "PC_FileExistingMsg":"当該ファイルは存在しています。",
      "PC_FileNotExistingMsg":"当該ファイルを見つかりませんでした。",
      "PC_PageCustomized":"当該ページにカスタマイズ内容が含まれています。",
      "PC_UserHasPermssionOnDocument":"当該ユーザーは当該ドキュメントを閲覧するための権限を持っています。",
      "PC_UserHasNoPermssionOnDocument":"当該ユーザーは当該ドキュメントを閲覧するための権限を持っていません。",
      "PC_DocumentIsInDraft":"当該ドキュメントはドラフト状態になっています。",
      "PC_DocumentIsNotInDraft":"当該ドキュメントはドラフト状態になっていません。",
      "PC_ListSecurityLevelHasIssue":"当該ライブラリーはアイテム作成者しかアイテムを閲覧/編集できないように設定されています。",
      "PC_ListSecurityLevelHasNoIssue":"当該ライブラリーはアイテム作成者しかアイテムを閲覧/編集できないように設定されていません。",
      "PC_LockDownEnabled":"制限付きアクセスのユーザーのアクセス許可ロックダウン モードが有効化されています。",
      "PC_LockDownNotEnabled":"制限付きアクセスのユーザーのアクセス許可ロックダウン モードが有効化されていません。",
      "PC_HasViewPermissionOnList":"当該ユーザーは当該ライブラリーを閲覧するための権限を持っています。",
      "PC_HasNoViewPermissionOnList":"当該ユーザーは当該ライブラリーを閲覧するための権限を持っていません。",
      "PC_TryDisable3PCode":"サードパーティーのコードの影響を除くために、ページ URL の末尾に ?disable3PCode を追加して新しいタブで開いてみてください。",
      "PC_LackPermissionOn":"The affected user lacks permission on",
      "PC_CanNotLoad":"がロードできませんでした！",
      "RemedySteps":"対処方法：",
      "CanBeFixedIn":"こちらで修正できます。",
      "ThisPage":"こちらのページ",   
      "RI_DeletedBy":"削除者:",
      "RI_PathFilter":"パスでフィルダー",
      "RI_StartDate":"開始日時",
      "RI_SelectADate":"日時を指定...",
      "RI_EndDate":"終了日時",
      "RI_QueryItems":"アイテムを復元",
      "RI_Restore":"復元",
      "RI_Export":"エクスポート",
      "RI_Querying":"実行中",
      "RI_Queried":"Queried",
      "RI_Items":"items",
      "RI_Filtered":"filtered",
      "RI_In":"in",
      "RI_RestoreItemFrom":"Restoring item from",
      "RI_Seconds":"seconds",
      "RI_To":"to",
      "RI_PleaseWait":"Please wait",
      "RI_Restored":"Restored",
      "RI_WithErrorMessage":"with error message",
      "RI_DeletedDate":"削除日時",
      "RI_Path":"Path",
      "RI_DeletedByEmail":"削除者のメールアドレス",
      "RI_DeletedByName":"削除者の名前",
      "RI_NoData":"データがありませんでした",
      "RI_FullDocumentPath":"ドキュメントのフルパス",
      "RI_NotMatchListRootFolder":"リストのルートフォルダーに一致しません",
      "RI_FailedToLoadItem":"Failed to load item via",
      "RI_URLInvalid":"は有効な URL ではない、もしくは対象アイテムが存在しません。",
      "RI_ItemTypeUnKnow":"不明なアイテムタイプ",
      "RI_FailedToGetData":"リクエストからデータを取得できませんでした",
      "SD_DocumentPathCanNotBeNull":"影響を受けているドキュメントのフルパスを指定してください！",
      "SD_DocumentCanBeSearched":"当該ドキュメントは検索可能の状態になっています。",
      "SD_SearchByFullPathException":"ドキュメントをフルパスで検索するのを試みる時に例外が発生しました。エラーメッセージ：",
      "SD_IsWebNoCrawlException":"サイトの NoCrwal プロパティを確認する時に例外が発生しました。エラーメッセージ：",
      "SD_DectectedNocrawlList":"当該リストに NoCrawl が有効になっていることを検出しました。",
      "SD_IsListNoCrawlException":"リストの NoCrwal プロパティを確認する時に例外が発生しました。エラーメッセージ：",
      "SD_DectectedDisplayFormIsMissing":"表示フォームが存在しないことを検出しました。\"新規/表示/編集フォームが存在しない\" 診断を実施して修正してください。",
      "SD_IsListMissDisplayFormException":"リストの表示フォームが存在しているかを確認する時に例外が発生しました。エラーメッセージ：",
      "SD_TheNocrawlEnabledList":"当該リストでは NoCrawl が有効になっています。",
      "SD_TheNocrawlNotEnabledList":"当該リストでは NoCrawl が有効になっていません。",
      "SD_TheDisplayFormMissed":"当該リストの表示フォームが存在しません。",
      "SD_TheDisplayFormNotMissed":"当該リストの表示フォームが存在しています。",
      "SD_IsDocumentInDraftVersionException":"当該ドキュメントがドラフト状態になっているかを確認する時に例外が発生しました。エラーメッセージ：",
      "SD_FolderSkipDraftCheck":"はフォルダーであるため、ドラフト状態の確認をスキップします",
      "SD_NocrawlEnabledSite":"当該サイトでは NoCrawl が有効になっています。",
      "SD_NocrawlNotEnabledSite":"当該サイトでは NoCrawl が有効になっていません。",
      "OL_CheckingIssueForLibrary":"Checking issue for library",
      "OL_LockdownEanbled":"Limited-access user permission lockdown mode of the site collection has been enabled",
      "OL_LockdownNotEanbled":"Limited-access user permission lockdown mode of the site collection hasn't been enabled",
      "OL_HasEditPermssionOnLibrary":"The affected user has enough permssion to edit the library",
      "OL_LackEditPermssionOnLibrary":"The affected user lack enough permssion to edit the library",
      "OL_OfflineAvailability":"Offline Client Availability for the library has been set to",
      "OL_RequireCheckOut":"Require Check Out for the library has been set to",
      "OL_DraftItemSecurity":"Draft Item Security of this library has been set to",
      "OL_AnyUserCanRead":"Any user who can read items",
      "OL_EditUserCanRead":"Only users who can edit items",
      "OL_ApproverCanRead":"Only users who can approve items (and the author of the item)",
      "OL_ContentApproval":"Content Approval of this library has been set to",
      "OL_ValidationFormula":"Validation formula/message of this library is",
      "OL_OfflineAvailabilityForWeb":"Offline Client Availability has been set to",
      "OL_SchemaCheckPassed":"Schema check for this library passed.",
      "OL_ColumnHasBeenSetTo":"the column has been set to",
      "OL_Required":"Required",
      "OL_Formula":"ValidationFormula",
      "OL_ValidationMessage":"ValidationMessage",
      SS_DiagnoseResultLabel:"Diagnose result:",
      SS_FoundSite:"Found site with URL",
      SS_SiteNoExist1:"Site with URL",
      SS_SiteNoExist2:"doesn't exist",
      SS_NoCrawlEnabled1:"The nocrawl setting has been enabled for the site",
      SS_NoCrawlEnabled2:"or its parent",
      SS_SiteIndexEnabled1:"Site",
      SS_SiteIndexEnabled2:"is enabled for search index",
      SS_HaveAccess:"You have access to the site",
      SS_NoAccess:"You don't have 'Read' permissions to the site",
      SS_InMembers:"You are in the 'Members' group of the site",
      SS_NotInMembers:"You are not in the 'Members' group of the site",
      SS_Label_AffectedSite:"Affected Site:",
      SS_Label_CheckIssues:"Check Issues",
      SS_Label_FixIssues:"Fix Issues",
      SS_Message_Checking:"Checking ......",
      SS_Message_NoSearchResult:"No Search Result for the site.",
      SS_Ex_GetWebError:"Get exception when try to get web with error message",
      SS_Ex_IsWebNoCrawlError:"Get exception when try to check IsWebNoCrawl with error message",
      SS_Ex_GetUserInfoError:"Get exception when try to get user info with error message",
      SS_Message_ResultDuplicate:"Search Result in Duplicate for the site.",
      SS_Message_SiteSearchable:"The site is searchable.",
      SS_Message_FixSite:"Fix detected site search issues ......",
      SS_Ex_FixWebNoCrawlError:"Get exception when try to check FixWebNoCrawl with error message",
      SS_Ex_AddUserInMembersError:"Get exception when try to check AddUserinMembers with error message",
      SS_Message_FxiedAll:"Fixed all detected issues please try to reindex the affected site and wait for 20~30 minutes then verify it",
      SS_Message_SearchAndOffline:"Please access 'Search and Offline Availability' and select 'Yes' for 'Indexing Site Content'. ",
      SS_Message_WaitAfterFix:"After fixing all detected issues, please reindex the site and wait for 20~30 minutes then verify it. ",
      SS_Message_CheckPermissions:"Please check your permissions to the site",
      SS_Message_AddInMembers:"This is a group site. Please add yourself as a member of the group. Refer: https://docs.microsoft.com/en-us/sharepoint/troubleshoot/search/search-results-dont-appear-for-group-owners",
      UI_Label_AffectedSite:"JP Affected Site",
      UI_Label_Email:"JP Email of Affected User/Group",
      UI_CheckIssueforUser:"JP Check Issues",
      UI_FixIssues:"JP Fix issue",
      UI_Result1:"JP Display name in AAD is",
      UI_Result2:"JP display name in user info list is",
      UI_Result3:"JP Email in AAD is",
      UI_Result4:"JP email in user info list is",
      UI_Result5:"JP JobTitle in AAD is",
      UI_Result6:"JP JobTitle in user info list is",
      UI_Result7:"JP WorkPhone in AAD is",
      UI_Result8:"JP WorkPhone in user info list is",
      UI_NonAffectedSite:"JP Affected site can't be null or invalid!",
      UI_NonAffectedUser:"JP Affected user can't be null or invalid!",
      UI_FixEmail:"JP Fixing user info item with eamil",
      UI_NonAADUser:"JP In the AAD can't find any group or user with the email address",
      UI_NonUserListUser:"JP In the user info list can't find any user with the UPN",
      UI_OneUserAAD:"JP Get one user from AAD:",
      UI_OneGroupAAD:"JP Get one group from AAD",
      UI_NonUserListGroup:"JP In the user info list can't find any group with group Id", 
      UI_FixSuccess:"JP Fix in the user info list completed, please recheck for verfiying it.",
      UI_FixFailed:"JP Fix in the user info list failed.",
      UPD_CheckDepartment:"JP Check UserProfile Department",
      UPE_CheckEmail:"JP Check UserProfile Email",
      UPM_CheckManager:"JP Check UserProfile Manager",
      UPP_PhotoURL:"JP Picture URL from UAP is",
      UPP_PhotoAAD:"JP Picture from AAD:",
      UPP_PhotoUserProfile:" JP Picture from user profile:",
      UPP_PhotoSuccess:"jpPhotos are loaded, but if they are mismatched, please follow this article https://github.com/abrcheng/SharePointOnlineQuickAssist/tree/main/KBs/UAP/SyncPhotoFromADToSPO",
      UPP_PhotoFailed:"jpFailed to get the user photo from the user profie! Please consider to follow this article https://github.com/abrcheng/SharePointOnlineQuickAssist/tree/main/KBs/UAP/SyncPhotoFromADToSPO",
      UPP_NonAADPhoto:"jpFailed to get the user photo from the AAD! please consider to set the user photo in AAD https://github.com/abrcheng/SharePointOnlineQuickAssist/tree/main/KBs/UAP/SyncPhotoFromADToSPO",
      UPT_AADTitle:"JP obTitle from AAD is",
      UPT_UserProfileTitle:"JP JobTitle from User Profile is",
      UPT_UserInfoListTitle:"JP JobTitle from site user info list is",
      UPT_NonAADTitle:"JP Failed to get the user/job title from AAD!",
      UPT_NonSiteTitle:"JP Failed to get the user from the site!",
      UPT_FixSiteTitle:"JP Fixing JobTitle in the site ...",
      UPT_FixUserProfileTitle:"JP Fixing JobTitle user profile ...",
      UPT_FailedUserProfileTitle:"JP Fix JobTitle in the user profile failed.",
      UPT_SuccessUserInfoListTitle:"JP Fix JobTitle in the user info list completed, please recheck for verfiying it.",
      UPT_FailedUserInfoListTitle:"JP Fix JobTitle in the user info list failed."
    }
  });